// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeHBdFcexySt2iffwKYRAD8qEtWWgIhvc',
    appId: '1:1062120584377:web:bb72c06494ab381668d768',
    messagingSenderId: '1062120584377',
    projectId: 'flutter-chat-app-b72aa',
    authDomain: 'flutter-chat-app-b72aa.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b72aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk39d2lUD9NZmDyg5acfyYkG_mQecptrc',
    appId: '1:1062120584377:android:8feb6198b6ff1e1868d768',
    messagingSenderId: '1062120584377',
    projectId: 'flutter-chat-app-b72aa',
    storageBucket: 'flutter-chat-app-b72aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4sZwJ0YY3P3TL_y5SQu1ahV4EdeYPaaU',
    appId: '1:1062120584377:ios:10bdab623683a33768d768',
    messagingSenderId: '1062120584377',
    projectId: 'flutter-chat-app-b72aa',
    storageBucket: 'flutter-chat-app-b72aa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4sZwJ0YY3P3TL_y5SQu1ahV4EdeYPaaU',
    appId: '1:1062120584377:ios:10bdab623683a33768d768',
    messagingSenderId: '1062120584377',
    projectId: 'flutter-chat-app-b72aa',
    storageBucket: 'flutter-chat-app-b72aa.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeHBdFcexySt2iffwKYRAD8qEtWWgIhvc',
    appId: '1:1062120584377:web:0b637920a9c44d0b68d768',
    messagingSenderId: '1062120584377',
    projectId: 'flutter-chat-app-b72aa',
    authDomain: 'flutter-chat-app-b72aa.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b72aa.appspot.com',
  );
}
